### ISSUE TITLE
adder.py needs to be in the current working directory

### ISSUE THREAD

**Issue by UnixJunkie** [mooreryan/ocaml_python_bindgen#2]
or you get this kind of error:
```
Fatal error: exception E (<class 'ModuleNotFoundError'>, No module named 'adder')
```
Is there a way I can install this python file somewhere else, but so that
it could still be found at runtime?

**Comment by mooreryan** [comment]
Hey, this is a good question.  I'm working on adding a couple of examples to the repo to show how to do this correctly.  I will update you when they are ready!

**Comment by mooreryan** [comment]
The short answer is that you could set the `PYTHONPATH` environmental variable to wherever the python module you want to bind is located.  Or you can "install" the python package in the typical python way.

The longer answer....So I added some examples that may help you out. This one in particular has some modules that it's importing (https://github.com/mooreryan/ocaml_python_bindgen/tree/main/examples/importing_modules).  The readme in there is fairly detailed, so hopefully it will help.  Oh and as a bonus, the dune files shows how to set up dune rules to automatically generate the bindings when your specs are updated.

If you need more help, let me know.  Otherwise, feel free to close the issue!

**Comment by UnixJunkie** [comment]
Better answer, I asked to @thierry-martinez:
https://github.com/thierry-martinez/pyml/issues/77
So, simple answer,
```ocaml
let toto = Py.Import.import_module "toto"
```
Now, combine this with mirage/ocaml-crunch, and we can have an ocaml library/executable
which can embeds the few python files it needs!
--> deployment heaven

**Comment by mooreryan** [comment]
I saw that issue on the pyml repository as well.  Yes that is correct that you need to use `Py.Import.import_module`, and in fact, that is what `pyml_bindgen` is doing (see [here](https://github.com/mooreryan/ocaml_python_bindgen/blob/a6f9cbb68ec1407abbeea300eba7950f6d982f77/examples/importing_modules/lib/magic_dust.ml#L42) for example).

However, it doesn't change the fact that you will need to let Python know how to actually find the module.  The simplest way to do that is probably with the `PYTHONPATH` environment variable (or just installing the package).  This [readme](https://github.com/mooreryan/ocaml_python_bindgen/blob/a6f9cbb68ec1407abbeea300eba7950f6d982f77/examples/importing_modules/README.md) has an example of this.

(Perhaps I'm misunderstanding your question...?)

**Comment by mooreryan** [comment]
(But yes embedding the python file in the executable somehow would be very cool....)

**Comment by UnixJunkie** [comment]
ok, PYTHONPATH would be the basic way, so if should let opam install the python file somewhere and then reflect
this in PYTHONPATH

**Comment by mooreryan** [comment]
Sorry for the confusion...let me try an explain it a different way in case others have the same question as well.

If you have a python package installed in the "normal" way...say `pip install matplotlib` or whatever, then the pyml/pyml_bindgen generated library (which uses `Py.Import.import_module`)  will be able to find any of the matplotlib modules because it will be installed in a location in which python "looks" for modules.

If you want to use a  python module not installed with pip, conda, or whatever (e.g., just in some folder in your `projects` directory for example) then the (probably) best way to let python know about that module is to add the directory to the PYTHONPATH.

**Comment by UnixJunkie** [comment]
No problem, this is what I got from your explanations.
